### ISSUE TITLE
Support on proxyless testing environment

### ISSUE THREAD

**Issue by mcompastie** [brutus333/moon#1]
Hello,

Following the instructions to set up Jenkins CI for Moon with docker-compose works like a charm.

However, i've notified several backtracks from ``Install prereq``pipeline showing errors when fetching deps.

```
Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f34fdded470>: Failed to establish a new connection: [Errno -2] Name or service not known',))': /simple/pytest/
```

Although it doesn't seems to block nor interfere with the remainder of the test process, i've found it a bit curious, as none of proxy-related environment variable are set in my configuration.

Please find attached [here](https://github.com/brutus333/moon/files/1619742/consoleText.txt) the complete Moon test jobs output.

Have i missed something ?

Maxime

**Comment by brutus333** [comment]
Hello!
I wrongly assumed that you are running this behind a corporate firewall.
I fixed the Jenkinsfile now to unset empty proxy variables. Now it should work fine.
